# action.yml
name: 'Public sync'
author: 'Thomas Vérin <thomas.verin@sonarsource.com>'
description: 'Automatically sync public part of private repo to public repo'
runs:
  using: 'docker'
  image: 'Dockerfile'  
branding:
  icon: 'refresh-cw'
